---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-services-development
  labels:
    app: teacher-services-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teacher-services-development
  template:
    metadata:
      labels:
        app: teacher-services-development
    spec:
      nodeSelector:
        teacherservices.cloud/node_pool: applications
        kubernetes.io/os: linux
      containers:
      - name: teacher-services-development
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 64M
            cpu: 0.1
          limits:
            memory: 64M
            cpu: 1
