---
apiVersion: v1
kind: Service
metadata:
  name: teacher-services-development
spec:
  selector:
    app: teacher-services-development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
