name: Build No Cache

on:
  workflow_dispatch:

  schedule:
    - cron: '30 12 * * 0'
    # Will run once a week on Sunday afternoon

jobs:
  build-no-cache:
    env:
      DOCKER_REPOSITORY: ghcr.io/dfe-digital/teacher-services-tech-docs
      GITHUB_TOKEN: ${{ github.token }}
    outputs:
      docker-image-tag: ${{ steps.build-image.outputs.tag }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - run: bundle exec middleman build

    - name: Build without cache and push docker image
      id: build-image
      uses: DFE-Digital/github-actions/build-docker-image@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        context: .
        docker-repository: ${{ env.DOCKER_REPOSITORY }}
        max-cache: true
        reuse-cache: false
        snyk-token: ${{ secrets.SNYK_TOKEN }}
