name: Deploy to AKS production cluster

on:
  push:
    branches:
    - main
  schedule: # 06:00 UTC Mon-Fri
  - cron: '0 6 * * 1-5'
  workflow_dispatch:
  pull_request:
    branches:
    - main


env:
  DOCKER_IMAGE: ghcr.io/dfe-digital/teacher-services-tech-docs

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - run: bundle exec middleman build

    - name: Build and push docker image
      id: build-image
      uses: DFE-Digital/github-actions/build-docker-image@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        context: .
        max-cache: true
        reuse-cache: true
        snyk-token: ${{ secrets.SNYK_TOKEN }}

  deploy:
    if: github.event_name == 'push' || github.event_name ==  'schedule' || github.event_name ==  'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment: production
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1.2
      with:
        kubelogin-version: 'v0.1.6'

    - uses: azure/aks-set-context@v4
      with:
        resource-group: s189p01-tsc-pd-rg
        cluster-name: s189p01-tsc-production-aks
        use-kubelogin: true
        admin: 'false'

    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v5
      with:
        namespace: common-production
        manifests: |
          manifests
        images: ${{env.DOCKER_IMAGE}}:${{ github.sha }}
        annotate-namespace: false
        pull-images: false
