name: 'Tests'

on:
  pull_request: {}

jobs:
  unit_tests:
    name: 'Unit tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: 'Lint YAML'
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c #Pinned at v3.1.1
        with:
          file_or_dir: config/*.yml

      - name: 'Set up Ruby from .ruby-version'
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: 'Run tests'
        run: |
          bundle exec rake

      - name: 'Run linter'
        run: |
          bundle exec rubocop .
